name: 'Setup Python and Install Dependencies'

# No 'on' key here, as this action is intended to be called by other workflows.

description: 'Sets up Python 3.10 and installs dependencies from requirements.txt if it exists.'

runs:
  using: 'composite'
  steps:
  - name: Set up Python 3.10
    uses: actions/setup-python@v3
    with:
      python-version: "3.10"

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    shell: bash

